rockcraft:
  gradle:
    id: io.github.rockcrafters.rockcraft
    version: 1.0.0
    classpath: "io.github.rockcrafters.rockcraft:io.github.rockcrafters.rockcraft.gradle.plugin:1.0.0"
    class-name: com.canonical.rockcraft.gradle.RockcraftPlugin
    repository: gradlePluginPortal()
    default-task: build-rock
    description: |
      Plugin for rock image generation
    tasks:
      - create-rock
      - build-rock
      - create-build-rock
      - build-build-rock
      - push-rock
      - push-build-rock
    default-configuration: |
      rockcraft {
      }
  maven:
    id: io.github.rockcrafters:rockcraft-maven-plugin
    version: 1.0.0
    default-task: install :create-rock :build-rock
    description: |
      Plugin for rock image generation
    tasks:
      - install :create-rock :build-rock
      - :create-build-rock
      - install :create-rock :build-rock :push-rock


