name: PR-self-hosted

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ['self-hosted', 'amd64', 'noble']
    name: CI Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: sudo apt-get -y --update install maven
      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.21/candidate
      - name: Setup rockcraft
        run: |
          rm -rf /home/runner/.local/state/rockcraft/log/*
          sudo snap install rockcraft --classic
      - run: ./gradlew build -PexcludeTags=boot,maven-modification,maven-dependency --no-daemon --stacktrace
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
