name: PR-self-hosted

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ['self-hosted', 'amd64', 'noble']
    name: CI Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: ./gradlew build -PexcludeTags=boot,maven-modification,maven-dependency --no-daemon
